### ISSUE TITLE
Floorp vs Waterfox

### ISSUE THREAD

**Issue by fastcat001** [Floorp-Projects/Floorp#100]
Can you write a side by side comparison
on how Floorp compares to Waterfox?

**Comment by creeper-0910** [comment]
Thanks for the issue!
Why do you want to compare with waterfox?
No offense, just wondering.

**Comment by fastcat001** [comment]
@creeper-0910 Just for the non-technical users to clearly see the difference.

I already see the difference in favor of Floorp, just want Floorp to be maintained forever.

FOREVER, FOREVER, FOREVER, FOREVER.

Even after when you graduate and become non-student.

**Comment by surapunoyousei** [comment]
It's interesting to compare Floorp and Waterfox. We respect both  Waterfox and Firefox, and implement features so they don't overlap.

## Functions

<strong>Bottom line, Floorp is more than twice as powerful as Waterfox.</strong>

Floorp offers a design change feature not found in Waterfox and Firefox and more extensive settings than Waterfox for the tab bar.

(Waterfox also has a function to switch between Photon on G5 and Lepton on G4, but Floorp also provides Gnome UI, Fluent UI, Material UI, Firefox UI Fix, etc. in addition to Lepton and Photon. , provides features like forward compatibility that can be changed without relying on the theme.)

However, Waterfox is removing features that are "useless for Firefox users".  Floorp doesn't have Pocket by default, but Waterfox breaks it from the ground up.

Floorp also comes with the browser manager sidebar, the most powerful and cool feature among Firefox variants. It's as good as Opera's and Vivaldi's sidebars, with web panels, bookmarks sidebars, and history sidebars.

 Users of TST and other vertical tabs will benefit greatly from having two sidebars, allowing them to use vertical tabs without crushing the sidebar. This is highly rated and is what makes Floorp such a powerful browser.

(By the way, Web Panel can use container tabs, which is a function that does not share cookies, which is the same as Sidekick browser.)

Also, for add-ons, Floorp is clearly more extensible.

From a functionality standpoint, Floorp wins out.

## Privacy

Result：Floorp is slightly less privacy wise than Waterfox.

Like Waterfox, Floorp also removes telemetry from Mozilla, but does not remove new tab ads, etc., as they don't want to undermine the benefits of Mozilla's source code. For this reason, when first launched, Floorp communicates with Google, Amazon, etc. This isn't much of a problem, but haters will hate it.

 Also, Google API is used to get the icon of the web panel. Considering it's talking to Google every time it's started, it's also a no-no.  (That alone doesn't violate your privacy, though, because you're just downloading an image, not loading any HTML.)
However, Waterfox's idea and Floorp's idea differ only when it comes to Google Safe Browsing.  Waterfox appears to lack Safe Browsing, which prevents downloading malware and malicious software.  Floorp believes that Google Safe Browsing should be enabled as it downloads a list of malicious sites from Google and compares them for local safety. However, I didn't activate Waterfox, which I don't want Google in anyway. This is a different idea.

However, both are definitely private browsers of the highest standard. At least, it's decidedly private compared to most Chromium-based browsers.

## Trust

A clear win for Waterfox in terms of trust.
Of Floorp and Waterfox, Waterfox is obviously bigger, and Floorp is smaller, developed by Japanese students, so it's natural to have doubts about their ability to continue. I haven't decided when I will stop, but if something happens to my family, I might stop.

 Waterfox obviously has a lot of staying power as he is under the umbrella of a company called System1.  Alex Kantos, his Waterfox developer, has more money than the Floorp developer and could probably hire a developer.。

## Security

Floorp is clearly more secure in this regard.

 First, Waterfox will wait for the official release of Firefox before releasing updates.  Floorp does the opposite and provides security fixes earlier than official Firefox. This means that Floorp has fewer security vulnerabilities and fewer bugs from Firefox than Waterfox.

 Updating to the ESR 102 makes that clear too.  Floorp already provided an ESR102-based update before his 102.0.0 release, and Waterfox became 102-based a week after he dropped support for Firefox ESR91.
 
 ## But....

I've compared Floorp and Waterfox and they are both great browsers.  A small portion of Floorp's code is based on Waterfox (will be removed within a month)

 Floorp for scalability or Waterfox for stability? Decide for yourself which one is better.

**Comment by surapunoyousei** [comment]
Also, this is not a declaration of war against Waterfox. If you're watching this at Waterfox, let's contribute to the development of Mozilla Firefox together.

 We will continue to work as an organization to protect the publicity and openness of the web.

**Comment by fastcat001** [comment]
Thanks for an amazing response @surapunoyousei

**Comment by surapunoyousei** [comment]
If you can tell us your impressions and actual usage experience, please write on Reddit or Twitter. I will be happy to visit

**Comment by fastcat001** [comment]
@surapunoyousei even if we enable fingerprinting protection in Floorp, does it still provide less privacy than Waterfox?

I honestly like Waterfox logo more.

**Comment by surapunoyousei** [comment]
> @surapunoyousei even if we enable fingerprinting protection in Floorp, does it still provide less privacy than Waterfox? I honestly like Waterfox logo more.

Fingerprinting helps you become anonymous on the web.  Waterfox does not have this item in its settings. Originally, Floorp also has stronger tracker protection than Waterfox, with fewer tracks than Waterfox. Fingerprinting is already stronger than Waterfox as it only increases protection from trackers.

 I like the logo. matter of taste

**Comment by surapunoyousei** [comment]
Anyway, I'm the one providing the Japanese translation of Waterfox.  I like Mozilla.

**Comment by fastcat001** [comment]
@surapunoyousei that's amazing, I like seeing great firefox forks Floorp, Waterfox and Librewolf.

I do not want any of these projects to be abandoned ever.

**Comment by surapunoyousei** [comment]
yes. I'm in college with this browser project. I am a student, but I will use this project to take the university entrance exam.

 I have no intention of abandoning this project at all.

**Comment by fastcat001** [comment]
Are you writing a university entrance exam in Floorp?

Good Luck!
