### ISSUE TITLE
Floorp will "froze" on a network with limited Internet access 

### ISSUE THREAD

**Issue by KeyID7** [Floorp-Projects/Floorp#107]
## Describe the bug

<img width="964" alt="2022-10-15_121422" src="https://user-images.githubusercontent.com/59076521/195968552-b9790a5b-2b93-4b73-b883-df754ff069e9.png">

Floorp shows the above blank page on starting up no matter what the main page is. And clicking the menu button(the red-marked one) gets no response. After several minutes, everything goes well.

## To Reproduce

Connect to a network which needs a proxy server to access the whole Internet. In my case, the network can directly connect to the Mozilla domains but probably can't for the others. Then just start Floorp and confirm the bug. If you have started Floorp with a normal network, you need to close Floorp and re-open it after a while(to make some caches invalid I guess).
A network that can access the whole Internet or not connecting to a network doesn't reproduce the bug.

## Expected behavior
Normally start up.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Floorp Version: 10.6.0

**Comment by surapunoyousei** [comment]
Please Try Firefox ESR 102.3

It is work well？

**Comment by KeyID7** [comment]
> Please Try Firefox ESR 102.3
> 
> It is work well？

It works well.

**Comment by surapunoyousei** [comment]
Ok. understood.

It seems like a problem with the dependency between the internal name of the Floorp browser and the internal name of Firefox.

I think it's difficult to fix it, but I'd like to look into it.

**Comment by surapunoyousei** [comment]
I'm currently considering following the Rapid release, and I'll see if it can be solved by switching the original Firefox source to a method that doesn't change much.

**Comment by surapunoyousei** [comment]
Floorp is largely unbased on Waterfox, and the Waterfox source code is only used as part of the Windows version of the workflow used to build GitHub Actions. In other words, the Floorp browser itself does not use source code from other browsers.

Floorp does not use source code from other browsers, although it has learned some things from Waterfox.

There are two reasons why it is not based on other Firefox-derived browsers

Floorp should be independent.

If you build Floorp on top of the Waterfox source code, then you have to update Floorp after Waterfox does an update. It would definitely complicate things.

Also, using another browser's source code for a "purely Japanese browser" is a bad idea. This is because it makes it easier for other browsers to interfere with Floorp.

By building it on its own substrate, it maintains the highest functionality and performance of all Firefox derivatives.

--

Rapid Release Tracking

Rapid release tracking is quite a burden for us. This is because the Firefox source code is constantly changing to keep up with the latest web standards and features.

If we followed this, Floorp would be a buggy browser. This is not to say that we are not considering rapid release tracking, we just need to think it through.

**Comment by surapunoyousei** [comment]
In theses days, the file is not maintained. I’ll delete it.

**Comment by surapunoyousei** [comment]
> Interesting ! @surapunoyousei Thank you very much for this insight and this important information and all your efforts to make this marvelous browser!!
> 
> 私はあなたが「純粋に日本語ブラウザ」と言ったことに気づいたので、フロアプブラウザは日本語のみで、日本人のみを対象としていますか?英語はダメですか?最近フロアを見つけたので、まだ試していません。はい、理解しています。フロアが独立しているのは素晴らしいアイデアです💯
> 
> 私の提案は、例えばFirefoxとは異なる新しい興味深い機能をもたらすとき、waterfoxコードのいくつかの小さな選択部分を取ることです。
> 
> ハードウェアアクセラレーションAV1ビデオデコードは、サポートされているGPU(Intel Gen 11+、AMD RDNA 2はNavi 24、GeForce 30を除く)で有効になっています。Microsoft StoreからAV1ビデオ拡張機能をインストールすることも必要になる場合があります。Linuxでは、WebGLのパフォーマンスが向上し、多くのユーザーの消費電力が削減され、イベント処理中のWaterfoxおよびWindowServerのmacOSでのCPU使用率が削減されます。macOS、特にフルスクリーンでのソフトウェアデコードビデオの電力使用量を削減しました。これには、NetflixやAmazon Prime Videoなどのストリーミングサイトが含まれ、Intel GPU用のWindowsでビデオオーバーレイが有効になり、ビデオ再生中の電力使用量が削減されます。
> 
> したがって、FlorpブラウザはFirefoxとwaterfoxとクロムの最高のものを取ります.....そして、独自の新しい改善と例外的な機能を追加し、Florpはさらに壮大になります!
> 
> どうもありがとう!



> Interesting ! @surapunoyousei Thank you very much for this insight and this important information and all your efforts to make this marvelous browser!!
> 
> I notice that you said: "purely Japanese browser", so Floorp browser is only in Japanese language and intended only for Japanese people? there is no english language please? I haven't tried it yet because I found Floorp recently.... yes I understand and it is an excellent idea that Floorp is independent 💯 🥇
> 
> my suggestion is just to take some small selective parts of the waterfox code when it brings new interesting features different from firefox like for example:
> 
> Hardware-accelerated AV1 video decoding is enabled on Windows with supported GPUs (Intel Gen 11+, AMD RDNA 2 Excluding Navi 24, GeForce 30). Installing the AV1 Video Extension from the Microsoft Store may also be required, On Linux, improved WebGL performance and reduced power consumption for many users, Reduced CPU usage on macOS in Waterfox and WindowServer during event processing. Reduced the power usage of software decoded video on macOS, especially in fullscreen. This includes streaming sites such as Netflix and Amazon Prime Video, Video overlay is enabled on Windows for Intel GPUs, reducing power usage during video playback......
> 
> thus Floorp Browser will take the best of firefox and waterfox and chromium..... and add its own new improvements and exceptional functions and Floorp becomes even more magnificent!
> 
> Thanks a lot !

Thanks.


Floorp can also be used in languages other than Japanese. It supports more than 20 languages. You can use it in American English or British English.

Because Floorp is based on Firefox, you can get benefits such as speeding up Firefox at the same level as Waterfox, so there is no need to import patches from Waterfox.

The feature that I think is great will be implemented in the patch we wrote from scratch.

**Comment by surapunoyousei** [comment]
I understood this problem. but, Floorp has some source code. The Rapid Release version of Firefox is constantly changing, which also affects Floorp's source code.

But, ESR version of Firefox is stable & not  constantly changing.Based on the above, rapid release tracking will increase bugs and will not increase new features because of the large amount of time spent creating patches to track them. Therefore, we will not reverse this decision.

**Comment by surapunoyousei** [comment]
By the way, This issue is about "Floorp will "froze" on a network with limited Internet access". this  issue is off topic. plz make another one

**Comment by typeling1578** [comment]
Does this still work today?

**Comment by creeper-0910** [comment]
I am closing this issue as there has been no response to this issue.
If you encounter any problems, please comment on this issue.

**Comment by KeyID7** [comment]
Sorry for the late reply. There were some off-topic replies so I didn't notice the latest ones.

I confirmed this problem doesn't happen anymore in version 10.8.0. Thanks!
