### ISSUE TITLE
Possibility for semi auto update for mac version

### ISSUE THREAD

**Issue by 9tin9tin9** [Floorp-Projects/Floorp#12]
## Is your feature request related to a problem? Please describe.
In the 10.3.0 release note draft, it is said that auto update is not available in Mac version.

## Describe the solution you'd like
I came across [this question](https://developer.apple.com/forums/thread/110810) and thought is it possible to check for updates to download .pkg file in background, open it and let user to click 'install' to install the update.
I am not sure if this is feasible though.

**Comment by surapunoyousei** [comment]
I think this is nearly impossible, as Firefox doesn't provide a build of files in pkg format.

 As we are a small community, we cannot afford to spend time on this development. forgive me please.

Also, since 10.2.0, the function to check for updates is included, and I think that there is no problem so much.

**Comment by surapunoyousei** [comment]
If the update check finds an update, you will be notified when you click Download File.

 This is a dmg format installer
