### ISSUE TITLE
[Bug]: Floorp crashing on certain websites when h/w accel is enabled

### ISSUE THREAD

**Issue by unlux** [Floorp-Projects/Floorp#1266]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

the browser crashes after about 3-4 seconds of the loading of the landing page of web.whatsapp.com and while running browser benchmark -> speedometer3. 
but when i turn off hardware acceleration in the setting, it works.

### Reproduction Steps

1. open browser with h/w accel ON
2. visit web.whatsapp.com / browserbench.org/Speedometer3.0
3. watch the window disappear
4. open browser with h/w accel OFF
5. visit web.whatsapp.com / browserbench.org/Speedometer3.0
6. watch it work properly but without h/w accel

### Expected Behavior

the browser should load whatsapp web properly / speedometer-test properly and not crash.

### Actual Behavior

it crashes

### Screenshots

[Screencast from 2024-07-08 14-56-14.webm](https://github.com/Floorp-Projects/Floorp/assets/92749166/399464a1-3d24-467c-904c-d8326addea5d)

### Browser Version

Mozilla Floorp 11.14.1 

### Operating System

Arch Linux x86_64 running latest Linux Kernel

### Additional Context

i am on Wayland btw and have MOZ_ENABLE_WAYLAND=1 setup
tried wiping the browser and clean reinstalling multiple times, same issue, 

another small issue, when i start a new window, it uses default ui and switched to my set ui(flueiral ui)(same issue with others too) quickly, it is fast but it is notable, the delay is way more on xwayland.

**Comment by unlux** [comment]
after a reboot, i tried it on vanilla firefox and waterfox, facing the same issue there as well, it might be that something is wrong with my arch's install, i'm thinking about another fresh install soon. i have never faced this issue in my so many months of using floorp.

**Comment by regularentropy** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/89523758/46281f2f-1f59-4aa7-add5-8bcc17b1055e)

Cannot confirm on my side (Fedora, Wayland (Sway), Floorp Flatpak). 

Please try flatpak version

**Comment by unlux** [comment]
installing the flatpak now, 
can it have any relation to a missing font? (i had some missing icons so i installed some fonts i found on forums online)

**Comment by unlux** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/92749166/4fd5b844-2ae0-40d6-896d-263a9d64861a)
experiencing the same thing on the flatpak as well, same tests.

**Comment by unlux** [comment]
found some other bugs too, opening a local file causes a crash with the same error,
trying to access a crypto currency price charts  causes a crash with the same error,

**Comment by regularentropy** [comment]
No idea what's happening. Logs doesn't show much.

Most likely something wrong with your arch install.

**Comment by unlux** [comment]
alr, i'll just reinstall, thanks mate.

**Comment by unlux** [comment]
i am on NixOS now, everything was working fine with floorp on Wayland till i realied that it wasnt using the Nvidia GPU at all, tweaked some environment variables i found online for the same issue, and it started coming up on nvidia-smi. but it started crashing again. when it runs on xwayland it stops crashing and keeps using the dGPU. 

i ran MOZ_ENABLE_WAYLAND=1 WAYLAND_DEBUG=1 floorp and these are the last log
```
[3830100.872]  -> wl_display@1.sync(new id wl_callback@55)
[3830100.907] xdg_wm_base@30.ping(1109848)
[3830100.914]  -> xdg_wm_base@30.pong(1109848)
[3830100.918] wl_pointer@13.motion(1109848, 1487.00000000, 16.33593750)
[3830100.924] wl_pointer@13.frame()
[3830100.964] wl_display@1.delete_id(64)
[3830100.971] wl_display@1.error(wp_linux_drm_syncobj_surface_v1@73, 4, "No Acquire point provided")
Crash Annotation GraphicsCriticalError: |[0][GFX1]: Device reset due to WR context (t=23.9101) |[1][GFX1-]: GFX: RenderThread detected a device reset in PostUpdate (t=23.9101) |[2][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@73: error 4: No Acquire point provided
 (t=35.9535) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@73: error 4: No Acquire point provided

Gdk-Message: 12:38:10.379: Error 71 (Protocol error) dispatching to Wayland display.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=33.111) Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

``` 

and these on one time

```
3786587.506] wl_display@1.delete_id(80)
[3786587.522] wl_display@1.error(wp_linux_drm_syncobj_surface_v1@67, 4, "No Acquire point provided")
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@67: error 4: No Acquire point provided
 (t=1.69321) [GFX1-]: Wayland protocol error: wp_linux_drm_syncobj_surface_v1@67: error 4: No Acquire point provided

Gdk-Message: 12:37:26.865: Error flushing display: Protocol error
Exiting due to channel error.
Exiting due to channel error.
```

**Comment by unlux** [comment]
the variables that i found. willing to take criticism on them.
```
 environment.variables = {
    __NV_PRIME_RENDER_OFFLOAD=1;
    __NV_PRIME_RENDER_OFFLOAD_PROVIDER="NVIDIA-G0";
    # __GLX_VENDOR_LIBRARY_NAME="nvidia";
    __VK_LAYER_NV_optimus="NVIDIA_only";
    # Required to run the correct GBM backend for nvidia GPUs on wayland
    # Apparently, without this nouveau may attempt to be used instead
    # (despite it being blacklisted)
    GBM_BACKEND = "nvidia-drm";
    # Hardware cursors are currently broken on nvidia
    WLR_NO_HARDWARE_CURSORS = "0";
    # In order to automatically launch Steam in offload mode, you need to add the following to your ~/.bashrc: 
    XDG_DATA_HOME="$HOME/.local/share";

   # from https://github.com/TLATER/dotfiles/blob/e633195dca42d96f42f9aa9016fa8d307959232f/nixos-config/yui/nvidia.nix#L33
   environment.variables = {
   # Necessary to correctly enable va-api (video codec hardware
     # acceleration). If this isn't set, the libvdpau backend will be
     # picked, and that one doesn't work with most things, including
     # Firefox.
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";

     # Required to use va-api it in Firefox. See
     # https://github.com/elFarto/nvidia-vaapi-driver/issues/95
    MOZ_DISABLE_RDD_SANDBOX = "0";
    # It appears that the normal rendering mode is broken on recent
     # nvidia drivers:
     # https://github.com/elFarto/nvidia-vaapi-driver/issues/212#issuecomment-1585584038
    NVD_BACKEND = "direct";
     # Required for firefox 97+, see:
     # https://github.com/elFarto/nvidia-vaapi-driver#firefox
    EGL_PLATFORM = "wayland";
  };

```

**Comment by tom-gora** [comment]
Experience intermittent crashes like that with practically the same logs on wayland, flatpak, fedora. Sure to occur on browser start, takes me several tries and in the end it manages to get up. Then, when it's working, keeps working normally 99% of the time. Couldn't track the root cause yet.

**Comment by tom-gora** [comment]
Got to the PC to supply some additional info:
- ENV:wl-roots (hyprland)
-  Fedora 6.9.8-200.fc40.x86_64
-  flatpak install
-  MOZ_ENABLE_WAYLAND=1 set and wayland enforced by flatpak permissions via flatseal and showing in about:support
- AMD graphics card and acceleration on
>|WEBRENDER  : 
>  | default	| available		
>  | user	  | force_enabled | Force enabled by pref

logs from WAYLAND_DEBUG=1 (cut out all the mouse wiggling log spam) at the time of crash:

`[1506624.775] wl_pointer@21.frame()
[1506624.780] wl_pointer@21.motion(343783, 267.03125000, 282.28515625)
[1506624.784] wl_pointer@21.frame()
[1506624.788] wl_pointer@21.motion(343791, 267.03125000, 284.28515625)
[1506624.791] wl_pointer@21.frame()
[1506624.795] wl_pointer@21.motion(343793, 268.05078125, 284.28515625)
[1506624.798] wl_pointer@21.frame()
[1506624.803] wl_pointer@21.motion(343794, 268.05078125, 287.90625000)
[1506624.806] wl_pointer@21.frame()
[1506624.811] wl_pointer@21.motion(343797, 268.05078125, 291.67187500)
[1506624.815] wl_pointer@21.frame()
[1506624.820] wl_pointer@21.motion(343801, 270.42968750, 291.67187500)
[1506624.824] wl_pointer@21.frame()
[1506624.828] wl_pointer@21.motion(343807, 272.46093750, 291.67187500)
[1506624.832] wl_pointer@21.frame()
[1506624.836] wl_pointer@21.motion(343808, 272.46093750, 295.33593750)
[1506624.840] wl_pointer@21.frame()
[1506624.846] wl_pointer@21.motion(343814, 276.15625000, 299.03125000)
[1506624.849] wl_pointer@21.frame()
[1506624.855] wl_pointer@21.motion(343817, 278.52734375, 299.03125000)
[1506624.858] wl_pointer@21.frame()
[1506624.865] wl_pointer@21.motion(343821, 279.61718750, 299.03125000)
[1506624.869] wl_pointer@21.frame()
[1506624.875] wl_pointer@21.motion(343822, 279.61718750, 302.42968750)
[1506624.879] wl_pointer@21.frame()
[1506624.892] wl_pointer@21.motion(343850, 279.61718750, 305.69531250)
[1506624.896] wl_pointer@21.frame()
Gdk-Message: 23:00:01.478: Lost connection to Wayland compositor.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=15.4664) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=31.7213) Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=31.3966)     `

- on certain sites happens 100% (like whatsapp reported above, or flathub page for me) plus usually 100% on every system start (possibly some sites in the background sitting in my sessions causing this?)
- initially does not happen when clean profile launched but will return to the behaviour when browsing

- can confirm it's not only installs from built binary, flatpak's the same. 
- can confirm does not happen if x backend enforced instead of wayland
- for me does not happen on base FF running on wayland backend

I hope this helps in tackling this thing

**Comment by tom-gora** [comment]
Did not experience myself but found traces of ppl reporting possibly similar thing on ff:
[LINK](https://www.reddit.com/r/wayland/comments/1dwt0j7/firefox_loads_slowly_sometimes_randomly_on_arch/)

**Comment by tom-gora** [comment]
See:
[FF bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1743144)

This seems to be the thing and it seems Floorp is missing the capacity to do this load balancing preventing the wayland client from being kicked. Seems like this has been resolved by introducing wayland proxy. I am nowhere near competence to speak on the matters of how wayland works. Is this solution to be baked in with the client or with the compositor itself? Can anyone help determining if this should remain an issue tracker here, or should we go to our respective implementations to moan about it? ;) (like wlroots and/or hyprland in my case?) My guess is the responsibility lies with the package, as Floorp seems to be the only browser behaving this way on my system so clearly there is a differentiating factor there.

**Comment by tom-gora** [comment]
Additional details in case someone is competent to work on including the fix or at least breaking down mitigation steps for us peasants ;)

[LINK](https://mastransky.wordpress.com/2023/12/22/wayland-proxy-load-balancer/)

**Comment by seniordevel** [comment]
I see the same issue on Linux Manjaro which also is based on Arch Linux.
My Floorp was installed as flatpak packagage , version 11.15.0.
Disabling hardware acceleration fixed the issue for now.

@tom-gora 
Where to find your 'temp fix' binary ?

**Comment by tom-gora** [comment]
### @seniordevel I've been using floorp as detailed below for about a week now, and although it gets slowdowns on start at times there is no crashes this way and I still would keep the bug tracker open, as ideally it would be preferential to have the solution baked into a  browser itself to deal with wayland environment properly.
1. Clone from `stransky/wayland-proxy` and build yourself binary using compile script inside as described in documentation.
2. Put `wayland-proxy` bin in your path (~/.local/bin/ in my case but you could do system-wide if you prefer).
3. Grab a Floorp tarball from [RELEASES](https://github.com/Floorp-Projects/Floorp/releases), extract a directory where you prefer.  (again, I put it in ~/.local/share as I prefer it that way) 
4. For convenience I add an alias and  an export statements in my shell config:

```
export BROWSER="wayland-proxy MOZ_ENABLE_WAYLAND=1 ~/.local/bin/floorp"

alias floorp="wayland-proxy MOZ_ENABLE_WAYLAND=1 ~/.local/bin/floorp"
```
( adjust paths as you need them and add keybindings as needed to this string as you prefer in your environment )
5. If enable wayaland variable does not work for you and you land in x-wayland render mode regardless, export  it globally in your shell config.

Hope this helps :)

**Comment by unlux** [comment]
appreciate your input,
still waiting for an source fix as this would be extremely painful to do in nixos

**Comment by tom-gora** [comment]
@unlux You're welcome

**Comment by tom-gora** [comment]
Oh. I forgot one important bit. For `~/.local/bin/floorp` to work there needs to be a symlink to the binary in floorp directory wherever you end up placing it obviously ;)

**Comment by seniordevel** [comment]
> Hope this helps :)
Yes, thank you, just irritating was the path stransky/wayland-proxy, I expected an URL:  [https://github.com/stransky/wayland-proxy/releases/tag/1.2](url) 

After some more testing, I doubt my issue is the same as reported here. In case I apologize.

1. For me the issue also occurs with Firefox 128.0esr (64bit), in contrast to what @unlux  reported at the top (he checked that this problem is not occurring in the latest version of Firefox ESR).
But -for me- just running the benchmark for 10 seconds always makes ESR 128 crash. Also no need to open the Whatsapp page.
2. I am not explicitly on wayland as @unlux  mentioned. I did not set the MOZ_ENABLE_WAYLAND variable and 
as far as I know, my Manjaro KDE supports wayland, but still the X11 compositor is default.

Thus I think my issue is not Floorp specific, I should report at bugzilla.



A note, possibly of interest for similar future bug reports:
There are distributions like Manjaro, where you can easily disable the whole compositor in the settings GUI. Some websites even recommend to do so. I tested this 'feature' and as expected it makes things even worse. On certain sites Firefox/Floorp will crash even with h/w accel OFF. I think it is of advantage to be aware of this popular but destructive KDE setting.

**Comment by ziomek64** [comment]
> i've been launching floorp from the terminal with `MOZ_ENABLE_WAYLAND=0 floorp` ever since 😢
You can add this as env variable in .desktop file of floorp

Also when can we expect this fixed? I think it can be patched, because the official patch in firefox comes in 130 which is even beyond our next esr 128

**Comment by surapunoyousei** [comment]
What about ESR128?

**Comment by ziomek64** [comment]
I also wanna know if this was fixed now in 128

**Comment by surapunoyousei** [comment]
Floorp now supports Wayland so there should be no problem.

**Comment by nkeilar** [comment]
Still happening here, making it unusable. Crashing every 30 minutes

```
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[580199]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[580199]: Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=2399.8)
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576797]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[580103]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576800]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[578387]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576561]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576715]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576675]: Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown (t=3598.71) [GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576675]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576673]: Exiting due to channel error.
Aug 22 10:35:24 ubuntu-workstation floorp.desktop[576536]: Exiting due to channel error.
Aug 22 10:35:25 ubuntu-workstation systemd[3336]: app-gnome-floorp-572087.scope: Consumed 18min 33.021s CPU time.
```

I just installed latest version today from apt.

**Comment by uqtdev** [comment]
Same here. Same error, Installed on flatpak on Fedora Bazzite

**Comment by unlux** [comment]
i get the same errors on latest nvidia properitory drivers, but not on the old version of them.
i use ```535.154.05``` driver

**Comment by creeper-0910** [comment]
Did you really test it with Firefox ESR?
This is the same problem reported with Firefox ESR.

**Comment by unlux** [comment]
@creeper-0910  i have been facing the same issue in all firefox based browsers, namely Floorp, Zen, and Librefox.

**Comment by creeper-0910** [comment]
If this is the case, please report the problem to Mozilla as it is a Firefox issue.

**Comment by ziomek64** [comment]
> Did you really test it with Firefox ESR?
> This is the same problem reported with Firefox ESR.

They patched in Wayland fix in 130, you can do it too.

**Comment by surapunoyousei** [comment]
OK~

I cherry pick the commit. Could you post bugzilla link?

**Comment by ziomek64** [comment]
> OK~
> 
> I cherry pick the commit. Could you post bugzilla link?

I think it's this? https://bugzilla.mozilla.org/show_bug.cgi?id=1898476

**Comment by surapunoyousei** [comment]
Thanks. I cherry pick this commit

**Comment by surapunoyousei** [comment]
This patch is available on ESR 128. I apply this patch at next release.

**Comment by ziomek64** [comment]
> This patch is available on ESR 128. I apply this patch at next release.
> ![image](https://github.com/user-attachments/assets/c61fbda5-8b37-403a-945c-cb500a734616)
> 

Nice

**Comment by OzzyHelix** [comment]
I am having this exact issue when trying to watch youtube

**Comment by OzzyHelix** [comment]
it appears to be fixed in upstream firefox I ran firefox developer edition and it works just fine. the issue seems to be with the esr base that floorp uses

**Comment by ioc2e3** [comment]
Not sure if it's because of the old hardware ...

On Windows ...

Firefox-based web-browser ...
Chrome-based web-browser ...

As long as ( hardware acceleration is turned on ) ...

The web-browser will crash ...

.
