### ISSUE TITLE
[Bug]: Workspaces reset on browser close/open when Container tabs are enabled and "Open previous windows and tabs" is unchecked

### ISSUE THREAD

**Issue by villainous-j** [Floorp-Projects/Floorp#1364]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [ ] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

When closing and then re-opening Floorp, any changes to workspaces will disappear, resetting back to the single default workspace. This issue only seems to occur when Container tabs are enabled, and if "Open previous windows and tabs" is unchecked.

If "Open previous windows and tabs" is checked, the same issue can be reproduced by opening a new window.

### Reproduction Steps

1. Ensure Container tabs are enabled.
2. Ensure "Open previous windows and tabs" is unchecked.
3. Rename the default workspace.
4. Close the browser.
5. Open the browser.
6. Notice the workspace has reset back to 'default'.

### Expected Behavior

Any changes to the workspaces should remain after closing/opening the browser.

### Actual Behavior

The workspaces will fully reset, leaving only the default workspace in the default condition.

### Screenshots

![image](https://github.com/user-attachments/assets/09f16182-2798-4c53-91d2-904a5a9c8106)

### Browser Version

11.17.4

### Operating System

Windows 11

**Comment by villainous-j** [comment]
Just added some changes to this issue as I've found it is easier to reproduce when "Open previous windows and tabs" is unchecked. However, even if "Open previous windows and tabs" is checked, opening a new window seems to also load without any workspace changes.

**Comment by surapunoyousei** [comment]
Workspaces are not shared between windows. This is because they are tied to each window.

This means that if you do not restore a previously opened window, the workspace will be discarded

**Comment by LongueBarcheNoir** [comment]
Hi there,
I must say I agree with @villainous-j . This "workspaces" feature is useful only if Floorp saves our customizations of different workspaces without being tied to opened tabs.
I don't need the browser to save my currently opened tabs, what I need is the isolation of miscellaneous websites in configured containers, set to always open in said containers.
In contrast, I currently still use Firefox and the latest "Firefox Multi-Account Containers" since I can set specific websites to always open in a specific container. I miss the "grouping" feature that the "Workspaces" could bring if it would work as expected.
There's definitely something to improve here I think @surapunoyousei and great work by the way ! ;)
