### ISSUE TITLE
[Bug]: Floorp Updates says "Updates disabled by your organization"

### ISSUE THREAD

**Issue by NandiyaLive** [Floorp-Projects/Floorp#1429]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

I've installed Floorp using AUR and it doesn't auto update.

### Reproduction Steps

1. Install Floorp using [AUR](https://aur.archlinux.org/packages/floorp-bin)
2. Check Settings > General > Floorp Updates

### Expected Behavior

This is how it looks like in Firefox
![image](https://github.com/user-attachments/assets/541a3d30-949a-44b2-8739-be547b076ae0)

### Actual Behavior

Floorp Updates says "Updates disabled by your organization"

### Screenshots

![image](https://github.com/user-attachments/assets/3b6a5240-6783-4a47-bfa5-db16eb3c409e)

### Browser Version

11.18.1

### Operating System

Manjaro 24.1.0pre1 Xahea

**Comment by typeling1578** [comment]
In the AUR version, updates are **not** managed by Floorp.

For example, if you are using the AUR helper named yay:
```
yay -Syu
```

**Comment by WavesOfSalt** [comment]
It doesn't make a lick of sense to have this "not planned". Is there a comment about this anywhere or is it actually meant to be a feature? The default behavior of Floorp is to force the policies to always  be "DisableAppUpdate": false, otherwise, show error <img width="113.833333" height="87.6666665" alt="Image" src="https://github.com/user-attachments/assets/cd4d217c-5b03-4059-aecb-19be6e459814" /> and refuse to run. You can get that error by setting the policy file to read-only. The only things on the list are just 
{
  "policies": {
    "DisableAppUpdate": false,
    "DontCheckDefaultBrowser": true
  }
}
Automatic updates have been broken since 2024, guys.
