### ISSUE TITLE
Provide a real Privacy Policy

### ISSUE THREAD

**Issue by candroid-man** [Floorp-Projects/Floorp#157]
It is unclear exactly what data you collect and how it is used.

**Comment by regularenthropy** [comment]
> It is unclear exactly what data you collect and how it is used.

There was already a discussion about privacy of the Floorp Browser at #51

**Comment by candroid-man** [comment]
Issue #51 has nothing to do with the privacy policy. You need to create a document that goes over everything

**Comment by kr-tukimi** [comment]
Hello, @candroid-man.

The group understands the need for a Floorp-specific privacy policy and is discussing the possibility of establishing one.
Please be patient.

And thanks for your reply, @regularenthropy!

**Comment by typeling1578** [comment]
New Privacy Policy
https://docs.ablaze.one/floorp_privacy_policy/

**Comment by candroid-man** [comment]
May I ask why it is necessary to collect user's IP addresses and user agents?

**Comment by typeling1578** [comment]
For example, to be able to respond in the event of a DoS attack on the server.
Normally we do not refer to these data.

**Comment by candroid-man** [comment]
Can this be disabled? I believe in stock Firefox you can disable this

**Comment by creeper-0910** [comment]
The user agent and OS name are used to apply the appropriate update data for the hardware when updating, but should not be sent until the update button is pressed.

**Comment by typeling1578** [comment]
> Can this be disabled? I believe in stock Firefox you can disable this

No.

**Comment by creeper-0910** [comment]
> Can this be disabled? I believe in stock Firefox you can disable this

Please use policies.json to set up the system to not receive updates.
That's all we can say.
https://github.com/mozilla/policy-templates/blob/master/README.md

**Comment by surapunoyousei** [comment]
> Can this be disabled? I believe in stock Firefox you can disable this

It means same as disable Firefox(Floorp) Updater. Librewolf do this. 

However, if we disable the update with Floorp aiming for a practical browser, users may suffer security damage. Will it be more damaging to disable updates in order to pursue user privacy or continue to increase security issues?

Although Floorp is made by a Japanese student community, we strive to improve our trust by disclosing personal information and signing software. We do not receive any profits directly from the browser and are operated by donation. There is no point in having personal information, and it is impossible to sell it.
