### ISSUE TITLE
Translate highlighted text and with right click

### ISSUE THREAD

**Issue by trimechee** [Floorp-Projects/Floorp#196]
Hello, One of the great features missing from firefox is being able to translate a web page on demand, i.e. right click / translate web page and also select a text and translate it just like chrome and ege browsers.... it will be great if our beloved Floorp Browser integrates these native features without extensions, thank you very much!

**Comment by surapunoyousei** [comment]
Well...

We have no translation sever. It's means that we cannot provide our original translation function. BTW, Mozilla is developing "Firefox Translation". It is useful for us. because It doesn't need translation server(It works offline)

If "Firefox Translation" provides Japanese translate function(still development), We may be going to provide native translation function.

**Comment by trimechee** [comment]
Great !! 👍 🥇

**Comment by surapunoyousei** [comment]
Firefox 115 has Translate feature.

**Comment by surapunoyousei** [comment]
All your past issues such as SSD issues have been resolved by Floorp 11's user.js feature. Rest assured.

![image](https://github.com/Floorp-Projects/Floorp/assets/73892113/73cf017f-da09-401d-b5a5-05d0261beb08)

**Comment by surapunoyousei** [comment]
Now you can install with just one button.  A reboot is required.

 If you provide a user.js of your choice, we will consider adding it.

**Comment by surapunoyousei** [comment]
In the screenshot, Floorp Default represents it.  You just need a backup if
your user.js used something not listed.

2023年6月18日(日) 23:39 trimechee ***@***.***>:
