### ISSUE TITLE
 0:09.22 ERROR: Cannot find gmake

### ISSUE THREAD

**Issue by Xarond12** [Floorp-Projects/Floorp#21]
hello i have problem when building from source 
i have installed make

**Comment by surapunoyousei** [comment]
Hi. @Xarond12 

Plz show me a error log. If U have it.

**Comment by surapunoyousei** [comment]
I can't say anything because I haven't seen the error log, but there is a possibility that you can fix it below.

 1. Create a file called mozconfig at the top of Floorp's clone repository.
 2. Open the mozconfig file with an editor and write the following:
```
ac_add_options --with-app-basename=Floorp
ac_add_options --with-app-name=floorp
ac_add_options --with-branding=browser/branding/official
ac_add_options --enable-bootstrap
```
3. Run ./mach configure.
4. Run ./mach build again

**Comment by Xarond12** [comment]
now it's working thanks

**Comment by surapunoyousei** [comment]
If anything happens again, feel free to contact us!
