### ISSUE TITLE
Betterfox with Floorp

### ISSUE THREAD

**Issue by golf1487** [Floorp-Projects/Floorp#233]
### Is your feature request related to a problem?

Floorp feels slower than official Firefox release, maybe because of Floorp having more features.

### Describe the solution you'd like

The possible slution would be to implement Betterfox's Fastfox .js by default:

https://github.com/yokoffing/Betterfox

However, as good as Betterfox is, it is not created for Firefox ESR you use for Floorp base.

Would you still be able to implement Betterfox?

### Describe alternatives you've considered

As an alternate solution, I was thinking of using Arkenfox ESR for Floorp by creating a new profile. Would you recommend doing that?

https://github.com/arkenfox/user.js/releases

**Comment by surapunoyousei** [comment]
Privacy can be worse with Betterfox in browsers other than Firefox; Firefox has a large user base and is relatively resistant to fingerprinting threats, while Floorp does not have as many users.

Betterfox modifies the behavior of various browsers. Floorp already behaves differently from Firefox due to restrictions such as Widevine. This is also true for other Firefox derivatives. So, if Floorp applies the Betterfox behavior, the website can use Floorp to detect that you have visited the website. This is fingerprint detection. For these reasons, we do not implement it.

As it says in Betterfox, if you want privacy, use Tor. We do not recommend its use, nor do we reject it. We do not endorse or reject the use of uBlock Origin, but we think it is more effective.

**Comment by Thorin-Oakenpants** [comment]
> Firefox has a large user base and is relatively resistant to fingerprinting threats

default Firefox is not resistant to uniquely fingerprinting users at all - if you do nothing, you are already uniquely identified - heck even a user agent and IP is almost enough and would catch 95% of users - modifying prefs for privacy gain is totally fine, even if it is fingerprintable - modifying prefs for perceived privacy but breaking functionality is a bit useless

if you want to add some further FPing protection (outside of blocking known scripts and users judiciously using uBlock Origin for content blocking and 3p), then your only hope without a proper built in browser solution, is to randomize a few common metrics and fool naive scripts, maybe - because you left your IP wide open (unless you use a VPN) - IP is a data point that can be used as a precise data point or even just a loose one - all fingerprints are fuzzy and just because your IP changes does not mean you can't be linked (behind the scenes, server level). This level, fooling naive scripts, does not require a crowd of users - so the number of users is irrelevant

what is Floorp even trying to achieve here?

**Comment by surapunoyousei** [comment]
This user.js change the network pref, this also seems difficult to accept. However, about half of the browser settings seem to be the same.

It looks like you are disabling the disk cache for speed. As there is a description that you should change it according to your preference, I think the answer is "No" if the set this pref default setting. There doesn't seem to be any point in copying all of this and making it the default.

 We do not restrict the use of this user.js, so it is recommended to use it according to your preference.

![image](https://user-images.githubusercontent.com/73892113/230567538-da924263-a251-4a73-b249-378cb83a5efa.png)

**Comment by surapunoyousei** [comment]
Hi！

I am currently creating a function to install user.js on Floorp with a single button.

This feature will be included in 11.0.0.

After a lot of thought, I decided it was best to create an option since should not change the default.

![20230511_171943.jpg](https://github.com/Floorp-Projects/Floorp/assets/73892113/3df8bdc0-a7fd-42dd-851d-800984e6062a)

**Comment by surapunoyousei** [comment]
yes.  Make sure ESR Fastfox is also selectable.

**Comment by yokoffing** [comment]
>  I hope, Betterfox dev introduces ESR configs

@golf1487 @surapunoyousei I will make an ESR115 branch in the next Betterfox release. Stay tuned.

**Comment by surapunoyousei** [comment]
Can’t wait for it :)

**Comment by yokoffing** [comment]
@surapunoyousei @golf1487 

ESR branch: https://github.com/yokoffing/Betterfox/tree/esr115

**Comment by surapunoyousei** [comment]
I'll change URL. Thanks

**Comment by surapunoyousei** [comment]
open "about:preferences#userjs"

**Comment by surapunoyousei** [comment]
Your current profile is this

**Comment by surapunoyousei** [comment]
Check the file.

Open profile DIR via about:support. open user.js

**Comment by surapunoyousei** [comment]
I'll create auto-update system

**Comment by yokoffing** [comment]
@surapunoyousei Just FYI: My intent is to not touch ESR prefs unless absolutely needed. Firefox ESR does not come with the latest features; it has the latest security and stability fixes. So I wouldn't prioritize an auto-update system.

**Comment by surapunoyousei** [comment]
Just make sure your changes can be applied immediately. You don't have to worry about that. I don't think I need to interfere with Betterfox directly, so I will be faithful to your changes.
