### ISSUE TITLE
[Feature Request] Tridactyl integration by default under Vim navigation mode

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Floorp-Projects/Floorp#264]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Your browser is what I was expecting for a long time. It is really good. I love it a lot. Lot of features. It'd be better to have an option to use Vim-based navigation mode via Tridactyl just like the integration of TST.

**Comment by surapunoyousei** [comment]
We will delete TST, Gesturefy and TWP from Floorp.

This is because those add-ons had not been adequately reviewed. They were brought to our attention by developers of other browsers.

Now, integration is almost impossible for the above reasons. Is there any merit to the inclusion of this add-on other more?

PS: I will add a post to the browser recommending that add-ons removed from inclusion be added to another alternative or somewhere else.

Also, if you are Japanese, you may write the issue in Japanese.

**Comment by surapunoyousei** [comment]
This seems like a difficult problem.

Chromium and Firefox are different, so they probably handle suspend differently.

We'll have to look into an alternative way to exclude pages.

**Comment by Marin-Kitagawa** [comment]
> We will delete TST, Gesturefy and TWP from Floorp.
> 
> This is because those add-ons had not been adequately reviewed. They were brought to our attention by developers of other browsers.
> 
> Now, integration is almost impossible for the above reasons. Is there any merit to the inclusion of this add-on other more?
> 
> PS: I will add a post to the browser recommending that add-ons removed from inclusion be added to another alternative or somewhere else.
> 
> Also, if you are Japanese, you may write the issue in Japanese.

No. What I meant was, "We should have a dedicated Vim mode for surfing". We can leverage the functionality of Tridactyl if possible.

**Comment by surapunoyousei** [comment]
I see.

It is necessary to confirm how much the function will be supported by users.

**Comment by surapunoyousei** [comment]
After much consideration, we have decided not to include this feature.

Sorry. We will implement features that are in demand, such as vertical tabs and tab groups in the native implementation, but they are too minor.
