### ISSUE TITLE
Floorp System extension is impossible to disable[Bug] 

### ISSUE THREAD

**Issue by slrgt** [Floorp-Projects/Floorp#358]
### Attention!

- [X] I undertand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

It's concerning this extension is on by default, impossible to turn off, and has access to so much data and even runs in Private Browsing

### To Reproduce

right click the Floorp System icon in the address bar
click manage extension
try to disable it
leave the tab
right click the Floorp System icon in the address bar
it is now on again

### Expected behavior

It should turn off when disabled and it should also never be allowed in Private Browsing

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/114287507/c98cc1db-abf6-4fe6-8c70-ac9b626fe956)

### OS Info

windows 10

### Floorp Version

11.1.0

**Comment by surapunoyousei** [comment]
This add-on is responsible for many core areas.

Web compatibility interventions, download notifications, update notifications, QR code generation, etc.

So it cannot be disabled, which is not a problem since Mozilla does the same thing. There is no code to run remotely either, so I guarantee there will be no problems.
