### ISSUE TITLE
[Bug] Linkedin does not work

### ISSUE THREAD

**Issue by golf1487** [Floorp-Projects/Floorp#636]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

Linkedin has loading issues, I restarted browser and I refreshed multiple times to work.
I only use ublock origin as an extension.

### To Reproduce

please login linkedin to see

### Expected behavior

work as fine as Firefox ESR. why have you stopped releasing Floorp lite version,
I'm tired of Floorp bugs, caused by lots of buggy features.

### OS Info

Windows 10

### Floorp Version

11.7.1

**Comment by CutterKnife** [comment]
To answer only the latter, it is due to lack of resources.
In order to develop and maintain features, as well as support them, and add more versions from there, a lot of things are missing in the current situation. Please understand that they are still a small community.
If someone is willing to maintain Lightning on an ongoing basis, it could be revived.

**Comment by surapunoyousei** [comment]
I am a normal, very ordinary student and cannot spend all of my time on browsing.

If donations were collected I could concentrate on development instead of working, but that is not possible in my current state.

LinkedIn works in my environment. Please let me know the detailed status.

Please report bugs in detail.

**Comment by creeper-0910** [comment]
Since no reply has been received, this issue is closed.
