### ISSUE TITLE
[Bug] Twitch is not work 

### ISSUE THREAD

**Issue by yousseffjel** [Floorp-Projects/Floorp#642]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

i have problem i try sing up on twitch but give me this problem i try clear cache but noting happened
 

### To Reproduce

.

### Expected behavior

.

### Screenshots

![image](https://github.com/Floorp-Projects/Floorp/assets/37506107/fc2cae07-7d1a-4245-8d27-45218c74eaea)

### OS Info

Arch linux 

### Floorp Version

11.7.1

**Comment by surapunoyousei** [comment]
Did you change useraget?

**Comment by surapunoyousei** [comment]
I cannot find the bug

**Comment by DrkXo** [comment]
In my case i couldn't login because of enabling **"Resist Fingerprinting & IP address leaks"** 
![image](https://github.com/Floorp-Projects/Floorp/assets/22086701/8759e489-c9db-40be-ac54-40f06fd32abe)



You can try disabling it.

**Comment by surapunoyousei** [comment]
can't reproduce

**Comment by Houdeeny** [comment]
In my experience, this happens when Enhanced Tracking Protection setting is set to Strict. Try switching it to Standard, or turn it off on the Twitch site via the Shield icon at the leftmost part of the address bar.

![image](https://github.com/Floorp-Projects/Floorp/assets/69956794/d1a9fd1a-7679-492b-8eb5-34abced33923)

**Comment by angrykid8** [comment]
I am experiencing this also, none of the solutions in here worked

**Comment by CryoRenegade** [comment]
+1
