### ISSUE TITLE
Browser even can't restore tabs on restart

### ISSUE THREAD

**Issue by Flashwalker** [Floorp-Projects/Floorp#66]
Browser even can't restore tabs from prev session on restart.
And didn't saves window size.

**Comment by surapunoyousei** [comment]
Your environment is macOS？

**Comment by Flashwalker** [comment]
> Your environment is macOS？

No, it's Ubuntu 22.04 x64, Flatpak 1.14.0

Also  browser can't access `file:///` links

**Comment by surapunoyousei** [comment]
I see, I think it's flatpak problem.

we prepare to Deb package and you will be able to try it. but, deb package does not have auto update system,

https://github.com/Floorp-Projects/Floorp/releases/download/Pre1-v10.6.0/floorp-debian-amd64.zip

**Comment by regularenthropy** [comment]
> > Your environment is macOS？
> 
> No, it's Ubuntu 22.04 x64, Flatpak 1.14.0
> 
> Also browser can't access `file:///` links

To be able to open file:// links, you need to add `--file-forwarding` as a flatpak argument. (e.g., flatpak run --file-forwarding one.ablaze.floorp).

If you want a GUI solution for this, you can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal).
Go to Floorp in Applications Tab, scroll down to “Filesystem” section, and check “All user files” button.

![open-file](https://user-images.githubusercontent.com/89523758/192242894-7c3f4398-315a-4180-926f-092dcb879dba.gif)

Regarding the inability to restore sessions – everything works fine for me. You may have encountered this because some tabs failed to load because the browser was being shut down.

![session](https://user-images.githubusercontent.com/89523758/192241220-5a8b3050-7dfd-45c7-afe7-d7dd21ca4566.gif)

Used OS: Ubuntu 22.04 x64
Used Flatpak: Flatpak 1.12.7

**Comment by surapunoyousei** [comment]
There is no reply, so I will mark it as resolved.

**Comment by Flashwalker** [comment]
Flatpak tweak was not helpfull.
.deb package was.

But i found this browser is not really about privacy.
It trying to connect a lot of domains on startup, despite no ever connections was allowed by my firewall, since browser was installed, and no one site was ever requested by me:

```
location.services.mozilla.com
firefox.settings.services.mozilla.com
push.services.mozilla.com
detectportal.firefox.com
www.google.com (despite another default search engine was set)
unsplash.com (despite new tab images was disabled in settings)
smarttop.211.ru (smarttop it's my pc name and 211.ru it's a site of my ISP . Why Floorp stick them together and trying to access...)
twitter.com
www.youtube.com
www.amazon.com
twitter.com
blog.ablaze.one
www.wikipedia.org
www.facebook.com
www.reddit.com
www.amazon.com
www.facebook.com
www.wikipedia.org
```

**Comment by creeper-0910** [comment]
> Flatpak tweak was not helpfull. .deb package was.
> 
> But i found this browser is not really about privacy. It trying to connect a lot of domains on startup, despite no ever connections was allowed by my firewall, since browser was installed, and no one site was ever requested by me:
> 
> ```
> location.services.mozilla.com
> firefox.settings.services.mozilla.com
> push.services.mozilla.com
> detectportal.firefox.com
> www.google.com (despite another default search engine was set)
> unsplash.com (despite new tab images was disabled in settings)
> smarttop.211.ru (smarttop it's my pc name and 211.ru it's a site of my ISP . Why Floorp stick them together and trying to access...)
> twitter.com
> www.youtube.com
> blog.ablaze.one
> www.wikipedia.org
> www.facebook.com
> www.reddit.com
> www.amazon.com
> ```

https://github.com/Floorp-Projects/Floorp/issues/51#issuecomment-1250214696
Here is the full description.
We do not recommend denying the necessary connections.

**Comment by creeper-0910** [comment]
If the issue is not related to the current issue, please create a new issue or post it in Discussions.
