### ISSUE TITLE
[Bug]: White shuttering 

### ISSUE THREAD

**Issue by rafalohaki** [Floorp-Projects/Floorp#865]
https://github.com/Floorp-Projects/Floorp/assets/20607107/c32b06cd-859a-4a57-a7d1-be02629db37b

### Expected Behavior

working

### Actual Behavior

white shuttering, its mostly on websites with video preview as thumbnails

### Screenshots

video sent

### Browser Version

11.9.0

### Operating System

windows 11

**Comment by surapunoyousei** [comment]
It affected by DRM

**Comment by rafalohaki** [comment]
> It affected by DRM

i disabled DRM

the same issue on twitter

**Comment by surapunoyousei** [comment]
It works in almost all environments, so there must be a problem with your environment

**Comment by rafalohaki** [comment]
seeems like its my problem now, not browser.
all other browsers working fine tho.
kk

**Comment by Riptidel** [comment]
It happened to me while browsing on YouTube, but only with specific videos (here's one for an example: https://www.youtube.com/watch?v=KmKYknb_xJw&pp=0gcJCb8Ag7Wk3p_U).
Not only with videos, but also with certain animation like GitHub's intro page and some videos inside other issues.
Disabling the HW acceleration, the issue disappears.
This issue is not a thing on Firefox.
